INSERT INTO tiers (numTiers, nomTiers, adresseTiers, typeTiers_id) VALUES
-- Clients
('CLT001', 'Dupont Jean', '12 Rue de la Paix, Paris', 1),
('CLT002', 'Martin Marie', '45 Avenue des Champs, Lyon', 1),
('CLT003', 'Bernard Paul', '67 Boulevard Victor Hugo, Marseille', 1),
('CLT004', 'Petit Claire', '23 Rue des Fleurs, Nice', 1),
('CLT005', 'Robert Pierre', '56 Avenue de la Liberté, Toulouse', 1),
('CLT006', 'Richard Sophie', '89 Rue du Moulin, Bordeaux', 1),
('CLT007', 'Durand Louis', '34 Avenue du Général, Nantes', 1),
('CLT008', 'Lefevre Julie', '78 Rue du Château, Strasbourg', 1),
('CLT009', 'Simon Thomas', '90 Rue de la Gare, Lille', 1),
('CLT010', 'Laurent Sandrine', '11 Rue des Lilas, Rennes', 1),
('CLT011', 'Moreau Mathieu', '22 Avenue du Centre, Reims', 1),
('CLT012', 'Fournier Camille', '33 Rue de Provence, Le Havre', 1),
('CLT013', 'Girard Nicolas', '44 Rue des Prés, Saint-Étienne', 1),
('CLT014', 'Andre Hélène', '55 Avenue de la République, Toulon', 1),
('CLT015', 'Lemoine Alice', '66 Rue de la Mer, Grenoble', 1),
('CLT016', 'Roux Philippe', '77 Rue de l’Église, Dijon', 1),
('CLT017', 'Blanc Charlotte', '88 Rue des Jardins, Angers', 1),
('CLT018', 'Garnier Hugo', '99 Avenue des Peupliers, Nîmes', 1),
('CLT019', 'Faure Elise', '10 Boulevard des Nations, Metz', 1),
('CLT020', 'Renaud Olivier', '21 Rue de la Fontaine, Besançon', 1),
('CLT021', 'Lambert Nathalie', '12 Rue des Acacias, Amiens', 1),
('CLT022', 'Chevalier Marc', '23 Avenue des Roses, Limoges', 1),
('CLT023', 'Moulin Sarah', '34 Rue de la République, Perpignan', 1),
('CLT024', 'Masson Louis', '45 Avenue de la Liberté, Clermont-Ferrand', 1),
('CLT025', 'Giraud Elise', '56 Rue du Port, Brest', 1),
('CLT026', 'Perrin Jacques', '67 Boulevard de la Gare, Tours', 1),
('CLT027', 'Boucher Claire', '78 Rue des Primevères, Limoges', 1),
('CLT028', 'Roussel Hugo', '89 Avenue de la Victoire, Dijon', 1),
('CLT029', 'Bertin Laura', '90 Rue de la Liberté, Mulhouse', 1),
('CLT030', 'Nicolas Sophie', '11 Avenue de la Gare, Pau', 1),
('CLT031', 'Benoit Mathieu', '22 Rue du Général, Bayonne', 1),
('CLT032', 'Poirier Thomas', '33 Rue de la Gare, Ajaccio', 1),
('CLT033', 'Charpentier Hugo', '44 Rue des Prés, Montpellier', 1),
('CLT034', 'Parisot Hélène', '55 Rue de la Fontaine, Orléans', 1),
('CLT035', 'Rey Louis', '66 Avenue des Champs, Nancy', 1),
('CLT036', 'Rolland Camille', '77 Rue des Arbres, Caen', 1),
('CLT037', 'Martineau Philippe', '88 Avenue du Centre, Annecy', 1),
('CLT038', 'Guillet Sandrine', '99 Rue de la Gare, La Rochelle', 1),
('CLT039', 'Colin Nicolas', '10 Rue du Port, Rouen', 1),
('CLT040', 'Chauvin Marie', '21 Rue des Fleurs, Dunkerque', 1),
('CLT041', 'Perrot Lucie', '12 Avenue de la République, Saint-Malo', 1),
('CLT042', 'Renard Julien', '23 Boulevard des Nations, Poitiers', 1),
('CLT043', 'Leclercq Alice', '34 Rue de Provence, Laval', 1),
('CLT044', 'Vidal Maxime', '45 Rue du Moulin, Albi', 1),
('CLT045', 'Denis Elodie', '56 Avenue de la Liberté, Colmar', 1),
('CLT046', 'Dufour Paul', '67 Rue de la Gare, Tarbes', 1),
('CLT047', 'Riviere Sophie', '78 Rue de la Victoire, Quimper', 1),
('CLT048', 'Leroux Hugo', '89 Avenue des Peupliers, Agen', 1),
('CLT049', 'Gauthier Julie', '90 Boulevard des Prés, Vannes', 1),
('CLT050', 'Barbier Nicolas', '11 Rue de la Fontaine, Béziers', 1),
-- Fournisseurs
('FRN001', 'Société Fournitech', '100 Rue des Entrepreneurs, Paris', 2),
('FRN002', 'Groupe DistriPlus', '200 Avenue du Commerce, Lyon', 2),
('FRN003', 'TechnoPro', '300 Boulevard de l’Industrie, Marseille', 2),
('FRN004', 'Alimentaire & Co', '400 Rue du Marché, Nice', 2),
('FRN005', 'Bâtiment Solutions', '500 Avenue de la Construction, Toulouse', 2),
('FRN006', 'Transports Rapides', '600 Rue de la Gare, Bordeaux', 2),
('FRN007', 'Informatique Services', '700 Avenue du Numérique, Nantes', 2),
('FRN008', 'ElectroDistribution', '800 Rue de l’Énergie, Strasbourg', 2),
('FRN009', 'Mécanique Précise', '900 Boulevard des Ateliers, Lille', 2),
('FRN010', 'Papeterie Centrale', '101 Rue des Fournitures, Rennes', 2),
('FRN011', 'Société AgriFrance', '102 Avenue des Champs, Reims', 2),
('FRN012', 'Vêtements Pro', '103 Rue de la Mode, Le Havre', 2),
('FRN013', 'SoluMobil', '104 Rue de la Roue, Saint-Étienne', 2),
('FRN014', 'Groupe Béton', '105 Avenue de la Pierre, Toulon', 2),
('FRN015', 'Plomberie Experts', '106 Rue des Artisans, Grenoble', 2),
('FRN016', 'Chauffage & Clim', '107 Rue des Énergies, Dijon', 2),
('FRN017', 'Peinture & Décoration', '108 Rue des Couleurs, Angers', 2),
('FRN018', 'Revêtement Sol Mur', '109 Avenue des Travaux, Nîmes', 2),
('FRN019', 'Logistique Express', '110 Boulevard du Transport, Metz', 2),
('FRN020', 'AutoPièces France', '111 Rue des Moteurs, Besançon', 2),
('FRN021', 'Eau Pure', '112 Rue de la Source, Amiens', 2),
('FRN022', 'Matériaux France', '113 Boulevard des Matériaux, Limoges', 2),
('FRN023', 'Outillage Pro', '114 Rue des Outils, Perpignan', 2),
('FRN024', 'Bricolage Express', '115 Avenue du Bricoleur, Clermont-Ferrand', 2),
('FRN025', 'ElectroTech', '116 Rue des Circuits, Brest', 2),
('FRN026', 'Transport Sud', '117 Avenue des Transports, Tours', 2),
('FRN027', 'Restauration & Co', '118 Rue du Goût, Limoges', 2),
('FRN028', 'Cuisine Pro', '119 Rue des Chefs, Dijon', 2),
('FRN029', 'Mobilier Urbain', '120 Avenue des Bancs, Mulhouse', 2),
('FRN030', 'EcoMatériaux', '121 Rue Verte, Pau', 2),
('FRN031', 'Véhicules Utilitaires', '122 Boulevard des Roues, Bayonne', 2),
('FRN032', 'Boulangerie Centrale', '123 Rue du Four, Ajaccio', 2),
('FRN033', 'Ferronnerie Artisanale', '124 Rue des Métaux, Montpellier', 2),
('FRN034', 'Jardin & Paysage', '125 Avenue des Fleurs, Orléans', 2),
('FRN035', 'Isolation Parfaite', '126 Rue de l’Hiver, Nancy', 2),
('FRN036', 'Peintures et Finis', '127 Boulevard des Couleurs, Caen', 2),
('FRN037', 'Climatisation Sud', '128 Rue des Énergies, Annecy', 2),
('FRN038', 'Décoration Murale', '129 Rue des Artistes, La Rochelle', 2),
('FRN039', 'Vitrages Sécurisés', '130 Boulevard des Vitrages, Rouen', 2),
('FRN040', 'Quincaillerie Générale', '131 Avenue du Bâtiment, Dunkerque', 2),
('FRN041', 'Équipements Agriculteurs', '132 Rue des Champs, Saint-Malo', 2),
('FRN042', 'Soudure & Métal', '133 Boulevard des Soudeurs, Poitiers', 2),
('FRN043', 'Papeterie Fine', '134 Rue des Livres, Laval', 2),
('FRN044', 'Pompes et Vannes', '135 Avenue des Flux, Albi', 2),
('FRN045', 'Hydraulique Pro', '136 Rue des Pressions, Colmar', 2),
('FRN046', 'Robinetterie Française', '137 Boulevard de l’Eau, Tarbes', 2),
('FRN047', 'Textiles Urbains', '138 Rue des Tissus, Quimper', 2),
('FRN048', 'Verres et Cristaux', '139 Avenue des Lumières, Agen', 2),
('FRN049', 'Menuiserie Bois', '140 Rue des Charpentiers, Vannes', 2),
('FRN050', 'Systèmes Alarmes', '141 Rue de la Sécurité, Béziers', 2);